# Build script used by gitlab.medelexis.ch
stages:
    - build
    - trigger_other_builds

build:
  stage: build
<<<<<<< Upstream, based on origin/master
  script: 
  - xvfb-run mvn clean verify -B -Pall-archs
  - jo token="$WEBHOOK_TOKEN" binary=%$(find ch.elexis.core.p2site/target/ch.elexis.core.p2site*.zip) destDir=$CI_COMMIT_REF_NAME/p2/elexis-3-core | curl -k -H "Content-Type:application/json" -X POST -d @- $WEBHOOK_URL/deploy-zip
  - for file in ch.elexis.core.product/target/products/*.zip; do jo token="$WEBHOOK_TOKEN" destFilename="${file##*/}" binary=%${file} destDir=$CI_COMMIT_REF_NAME/products/ | curl -k -H "Content-Type:application/json" -X POST -d @- $WEBHOOK_URL/deploy-file; done
  only:
  - master@elexis/elexis-3-core
  - /^\d*[.]\d*$/@elexis/elexis-3-core
  - /^[bf]\d*$/@elexis/elexis-3-core
=======
  script: xvfb-run mvn clean verify -B -Pall-archs
  artifacts:
    paths:
    - ch.elexis.core.product/target/products/*.zip
    - ch.elexis.core.p2site/target/*.zip
    expire_in: 1 day

deploy_artifacts:
    stage: deploy
    script:
    - mkdir upload; unzip ch.elexis.core.p2site/target/ch.elexis.core.p2site*.zip -d upload/
    - ch.elexis.core.releng/upload-dav.sh upload/ https://download.elexis.info/elexis/ $CI_COMMIT_REF_NAME/p2/elexis-3-core $DEPLOY_USER $DEPLOY_PASSWORD
    - rm -Rf upload/
    - ch.elexis.core.releng/upload-dav.sh ch.elexis.core.product/target/products/ https://download.elexis.info/elexis/ $CI_COMMIT_REF_NAME/products $DEPLOY_USER $DEPLOY_PASSWORD
    environment:
        name: elexis-3-core/$CI_COMMIT_REF_NAME
        url: http://download.elexis.info/elexis/$CI_COMMIT_REF_NAME/p2/elexis-3-core
    only:
    - master@elexis/elexis-3-core
    - /^\d*[.]\d*$/@elexis/elexis-3-core
<<<<<<< Upstream, based on origin/master
>>>>>>> a46985b [6143] Remove pom.xml additional repository, just use target
=======
    - /^[bf]\d*$/@elexis/elexis-3-core
>>>>>>> 9778d98 [6143] gitlab pipeline pick up [bf]\d.* branches

trigger_elexis-3-base_build:
    stage: trigger_other_builds
    script:
    - "curl -X POST -F token=$TRIGGER_TOKEN_ELEXIS_3_BASE -F ref=$CI_COMMIT_REF_NAME https://gitlab.medelexis.ch/api/v4/projects/14/trigger/pipeline"
    only:
    - master@elexis/elexis-3-core
    - /^\d*[.]\d*$/@elexis/elexis-3-core
    - /^[bf]\d*$/@elexis/elexis-3-core
