---
language: java
script: 
  - mvn --version
  - mvn clean install -f ch.elexis.core.releng/pom.xml
  
notifications:
  email:
  - niklaus.giger@member.fsf.org
jdk:
  - openjdk6
  - oraclejdk7
  - openjdk7

# whitelist of branches to build
branches:
  only:
    - master
