name: Java CI with Maven

on:
  push:
     branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      TARGET:
        description: 'Elexis-Target to build against' 
        required: true
        default: '2023-09-java17'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Build Image
      run: docker pull ghcr.io/elexis/docker-build:${{ github.event.inputs.TARGET }}
    - name: Build with Docker
      run:  docker run --rm --init -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven ghcr.io/elexis/docker-build:${{ github.event.inputs.TARGET }} xvfb-run mvn -V clean verify -B
